# Generated by Django 5.0.6 on 2024-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_gestion_campaña', models.CharField(max_length=100)),
                ('Tipo_documento', models.CharField(max_length=100)),
                ('Numero_documento', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
                ('Fecha_gestion', models.DateTimeField()),
                ('Tipo_llamada', models.CharField(max_length=20)),
                ('Codigo_gestion', models.CharField(max_length=100)),
                ('Resultado', models.CharField(max_length=50)),
                ('Fecha_compromiso', models.DateTimeField()),
                ('Nombre_asesor', models.CharField(max_length=100)),
                ('Campaña', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=20)),
                ('Obligacion', models.CharField(max_length=100)),
                ('Nro_comparendo', models.CharField(max_length=100)),
                ('Valor', models.CharField(max_length=50)),
            ],
        ),
    ]
