# Generated by Django 5.0.6 on 2024-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='Fecha_compromiso',
            field=models.CharField(max_length=100),
        ),
    ]
