# Generated by Django 5.0.6 on 2024-05-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0004_alter_gestion_fecha_compromiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='Fecha_compromiso',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
