# Generated by Django 5.0.6 on 2024-05-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0005_alter_gestion_fecha_compromiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='Fecha_compromiso',
            field=models.DateTimeField(null=True),
        ),
    ]
