# Generated by Django 5.0.6 on 2024-05-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0006_alter_gestion_fecha_compromiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_cliente', models.CharField(max_length=100)),
                ('Nit_cliente', models.CharField(max_length=100)),
                ('Numero_obligacion', models.CharField(max_length=200)),
                ('Fecha_pago', models.DateTimeField()),
                ('base', models.CharField(max_length=200)),
                ('Fecha_gestion', models.DateTimeField()),
                ('Aplicacion_gestion', models.CharField(max_length=200)),
                ('Fecha_sms', models.DateTimeField()),
                ('Campaña', models.CharField(max_length=200)),
                ('Aplicacion_sms', models.CharField(max_length=200)),
                ('Aplicacion_final', models.CharField(max_length=200)),
                ('Fecha_sencilla', models.DateTimeField()),
                ('Año', models.CharField(max_length=100)),
                ('Dia', models.CharField(max_length=100)),
                ('Mes', models.CharField(max_length=100)),
                ('Semana', models.CharField(max_length=100)),
                ('Numero_Mes', models.CharField(max_length=100)),
                ('Nombre_dia_semana', models.CharField(max_length=100)),
                ('Cruce_sms', models.CharField(max_length=100)),
            ],
        ),
    ]
