# Generated by Django 5.0.6 on 2024-05-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0007_pagos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='Aplicacion_gestion',
            new_name='Valor_pago',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='Aplicacion_sms',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='Año',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='Campaña',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='Cruce_sms',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='Dia',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='Fecha_gestion',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='Fecha_sms',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='Mes',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='Nombre_dia_semana',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='Numero_Mes',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='Semana',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='base',
        ),
    ]
