# Generated by Django 5.0.6 on 2024-05-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0008_rename_aplicacion_gestion_pagos_valor_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CruceRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula_cliente', models.CharField(max_length=200)),
                ('Cod_gestion', models.CharField(max_length=200)),
                ('Nombre_asesor', models.CharField(max_length=200)),
                ('Fecha_gestion', models.DateTimeField(null=True)),
                ('Valor_pago', models.CharField(max_length=200)),
                ('Fecha_pago', models.DateTimeField(null=True)),
            ],
        ),
    ]
