# Generated by Django 5.0.6 on 2024-05-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0009_cruceregistro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CruceRegistro',
        ),
        migrations.AddField(
            model_name='pagos',
            name='Mes',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
