# Generated by Django 5.0.6 on 2024-05-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0010_delete_cruceregistro_pagos_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='Mes',
        ),
    ]
